export {default as Cards} from './Cards/Cards'
export {default as Chart} from './Chart/Chart'
export {default as CountryPicker} from './CountryPicker/CountryPicker'
export {default as Footer} from './Footer/Footer'
export {default as Navbar} from './Header/Navbar'
export {default as Header} from './Header/Header'
export {IndoData} from './indoData/IndoData'
export {default as VaksinIndo} from './VaksinIndo/VaksinIndo'
export {Hospital} from './Hospital/Hospital'
export {default as HoaxCards} from './HoaxCards/HoaxCards'
export {default as Pagination} from './HoaxCards/Pagination'
export {default as AdminHomeComponent} from './Admins/AdminHomeComponent'
export {default as AdminDataComponent} from './Admins/AdminDataComponent'
export {default as AdminLoginComponent} from './Admins/AdminLoginComponent'
export {default as InfoCardComponent} from './Info/InfoCardComponent'
export {default as InfoComponent} from './Info/InfoComponent'
export {default as InfoDetailComponent} from './Info/InfoDetailComponent'
export {default as AdminEditInfo} from './Admins/AdminEditInfo'
export {default as AdminAddInfo} from './Admins/AdminAddInfo'